config/routes.rb
RedditClone::Application.routes.draw do

  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :links do
      resources :comments, only: [:create]
    end
  end

  resources :comments, only: [:show]

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  body              :text             not null
#  parent_comment_id :integer
#  link_id           :integer          not null
#  user_id           :integer          not null
#  created_at        :datetime
#  updated_at        :datetime
#

class Comment < ActiveRecord::Base

  validates :body, :link_id, :user_id, presence: true

  belongs_to :link
  belongs_to :author, class_name: "User", foreign_key: :user_id
  has_many :comments, class_name: "Comment", foreign_key: :parent_comment_id
  has_many :subs, through: :link, source: :subs

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  body       :string(255)
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  url        :string(255)      default(""), not null
#

class Link < ActiveRecord::Base

  validates :title, :url, :user_id, presence: true

  belongs_to :op, class_name: "User", foreign_key: :user_id
  has_many :comments
  has_many :memberships, class_name: "LinkSub", foreign_key: :link_id
  has_many :subs, through: :memberships, source: :sub

end

app/models/link_sub.rb
# == Schema Information
#
# Table name: link_subs
#
#  id         :integer          not null, primary key
#  link_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class LinkSub < ActiveRecord::Base

  belongs_to :link
  belongs_to :sub

  validates :link_id, :sub_id, presence: true

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Sub < ActiveRecord::Base

  belongs_to :admin, class_name: "User", foreign_key: :user_id
  has_many :comments, through: :links, source: :comments
  has_many :memberships, class_name: "LinkSub", foreign_key: :sub_id
  has_many :links, through: :memberships, source: :link

  validates :name, :user_id, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base

  attr_accessor :password

  validates :username, :password, presence: true
  validates :password, length: { minimum: 6 }
  validates :username, uniqueness: true

  has_many :subs
  has_many :links
  has_many :comments

  def password=(plain_text)
    @password = plain_text
    self.password_digest = BCrypt::Password.create(plain_text) if @password
  end

  def is_password?(plain_text)
    BCrypt::Password.new(password_digest).is_password?(plain_text)
  end

  def reset_session_token!
    self.session_token = SecureRandom.hex
    #password = params[:password]
    self.save!

    self.session_token
  end

  def self.find_by_credentials(user_credentials)
    user = User.find_by_username(user_credentials[:username])
    return user if user.try(:is_password?, user_credentials[:password])
    nil
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by_session_token( session[:token] )
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    user.password = user_params[:password]
    session[:token] = user.reset_session_token!
    @current_user = user
  end

  def logout!
    @current_user = nil
    session[:token] = SecureRandom.hex
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end


  private

  #if this doesn't work, copy paste to 2 controllers
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def destroy
  end

  def index
  end

  def edit
  end

  def update
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
    @link = Link.new
  end

  def create
    sub = Sub.find(params[:sub_id])
    @link = sub.links.new(link_params)
    if @link.save
      redirect_to sub_link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to subs_url
  end

  def index
    @links = Link.all
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(link_params)
      redirect_to sub_link_url(@link)
    else
      flash.now[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :body, :url, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(user_params)

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Incorrect username and/or password."]
      render :new
    end
  end

  def destroy
    logout!
    render :new
  end

  private

  #if this doesn't work, copy paste to 2 controllers
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_logged_in

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  def index
    @subs = Sub.all
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub = Sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])

    unless @user
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
  end

  private

  #if this doesn't work, copy paste to 2 controllers
  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    '<input type="hidden" value="form_authenticity_token" name="authenticity_token"></input>'.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<%= error %>
	<% end %>
<% end %>

<% if logged_in? %>
	Welcome, <%= current_user.username %>!<br>
	<%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
	<%= link_to "Sign In", new_session_url %>
	<%= link_to "Sign Up", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/destroy.html.erb
<h1>Links#destroy</h1>
<p>Find me in app/views/links/destroy.html.erb</p>

app/views/links/edit.html.erb
<h1>Links#edit</h1>
<p>Find me in app/views/links/edit.html.erb</p>

<form action="<%= sub_links_url(params[:id]) %>" method="POST">
	<%= auth_token %>

	<input type="hidden" name="_method" value="PATCH">

	<input type="hidden" name="link[user_id]" value="<%= current_user.id %>">

	<label> Title:
		<input type="text" name="link[title]"></input><br>
	</label>

	<label> Body:
		<input type="text" name="link[body]"></input><br>
	</label>

	<label> URL:
		<input type="text" name="link[url]"></input><br>
	</label>

	<button type="submit">Edit Link</input>

</form>

app/views/links/index.html.erb
<h1>Links#index</h1>
<p>Find me in app/views/links/index.html.erb</p>

app/views/links/new.html.erb
<h1>Links#new</h1>
<p>Find me in app/views/links/new.html.erb</p>

<form action="<%= sub_links_url(params[:id]) %>" method="POST">
	<%= auth_token %>

	<input type="hidden" name="link[user_id]" value="<%= current_user.id %>">

	<label> Title:
		<input type="text" name="link[title]"></input><br>
	</label>

	<label> Body:
		<input type="text" name="link[body]"></input><br>
	</label>

	<label> URL:
		<input type="text" name="link[url]"></input><br>
	</label>

	<button type="submit">Create Link</input>

</form>

app/views/links/show.html.erb
<h1>Links#show</h1>
<p>Find me in app/views/links/show.html.erb</p>

app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h1>Subs#new</h1>

<h1>Edit Sub</h1>

<form action="<%= subs_url %>" method="POST">

	<%= auth_token %>

	<input type="hidden" name="_method" value="PATCH">

	<input type="hidden" name="sub[user_id]" value="<%= current_user.id %>">

	<label> Name:
		<input type="text" name="sub[name]"></input><br>
	</label>

	<button type="submit">Edit</input>

</form>

app/views/subs/index.html.erb
<h1>Subs#index</h1>
<p>Find me in app/views/subs/index.html.erb</p>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="POST">
	<%= auth_token %>

	<input type="hidden" name="sub[user_id]" value="<%= current_user.id %>">

	<label> Name:
		<input type="text" name="sub[name]"></input><br>
	</label>

	<button type="submit">Create</input>

</form>

app/views/subs/show.html.erb
<h1>Subs#show</h1>
<p>Find me in app/views/subs/show.html.erb</p>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
	<%= auth_token %>
	<label> Username:
		<input type="text" name="user[username]"></input><br>
	</label>
	<label> Password:
		<input type="text" name="user[password]"><br>
	</label>

	<button type="submit">Sign Up</input>

</form>